importScripts("./assistant-config.js","./assistant-db.js");
const CACHE_NAME = "netsuper-business-record-v6-assist-3";
const OWNED_CACHE_PREFIX = "netsuper-business-record-";
const APP_SHELL = ["./","./index.html","./manifest.json","./assistant-config.js","./assistant-core.js","./assistant-db.js","./assistant.js","./icon-192.png?v=3","./icon-512.png?v=3","./apple-touch-icon.png?v=3","./audio/checkin.mp3","./audio/dispatch.mp3","./audio/arrival-1.mp3","./audio/load-1.mp3","./audio/load-2.mp3","./audio/load-3.mp3","./audio/load-4.mp3","./audio/load-5.mp3","./audio/load-6.mp3"];
self.addEventListener("install",event=>{event.waitUntil(caches.open(CACHE_NAME).then(cache=>cache.addAll(APP_SHELL)).then(()=>self.skipWaiting()))});
self.addEventListener("activate",event=>{event.waitUntil(caches.keys().then(keys=>Promise.all(keys.filter(key=>key!==CACHE_NAME&&key.startsWith(OWNED_CACHE_PREFIX)).map(key=>caches.delete(key)))).then(()=>self.clients.claim()))});
self.addEventListener("fetch",event=>{if(event.request.method!=="GET")return;const url=new URL(event.request.url);if(url.origin!==self.location.origin||url.pathname.includes("/api/"))return;event.respondWith(fetch(event.request).then(response=>{if(response.ok&&APP_SHELL.some(path=>new URL(path,self.registration.scope).href===event.request.url)){const copy=response.clone();caches.open(CACHE_NAME).then(cache=>cache.put(event.request,copy))}return response}).catch(()=>caches.match(event.request).then(cached=>cached||(event.request.mode==="navigate"?caches.match("./index.html"):Response.error()))))});
self.addEventListener("push",event=>{event.waitUntil((async()=>{let payload;try{payload=event.data.json()}catch{payload={title:"NS業務アシスト",body:"確認事項があります。",requiresAction:false}}const windows=await clients.matchAll({type:"window",includeUncontrolled:true}),visible=windows.some(c=>c.visibilityState==="visible");if(payload.requiresAction)await NSAssistDB.set("pendingPrompt",payload);await self.registration.showNotification(payload.title||"NS業務アシスト",{body:payload.body||"",icon:"./icon-192.png?v=3",badge:"./icon-192.png?v=3",tag:`ns-assist-${payload.eventId||Date.now()}`,renotify:true,silent:visible,data:payload,actions:payload.actions?.map(([action,title])=>({action,title}))||[]});if(visible)for(const client of windows)client.postMessage({type:"assist-event",payload});})())});
self.addEventListener("notificationclick",event=>{event.notification.close();event.waitUntil((async()=>{const payload=event.notification.data||{},directActions=['done','pending','working','synchro_done'];if(directActions.includes(event.action)){const id=crypto.randomUUID(),item={id,path:'/api/action',body:{sessionId:payload.sessionId,eventId:payload.eventId,action:event.action,actionId:id},createdAt:Date.now()};await NSAssistDB.putOutbox(item);const session=await NSAssistDB.get('session');if(session?.id===payload.sessionId){session.updatedAt=Date.now();if(event.action==='done')session.completed={...(session.completed||{}),[payload.eventId]:session.updatedAt};if(event.action==='synchro_done')session.synchroDoneAt=session.updatedAt;await NSAssistDB.set('session',session);}await NSAssistDB.set('pendingPrompt',null);const token=await NSAssistDB.get('installationToken'),base=String(NS_ASSIST_CONFIG.apiBase||'').replace(/\/$/,'');if(token&&base)try{const r=await fetch(base+item.path,{method:'POST',headers:{'Content-Type':'application/json',Authorization:`Bearer ${token}`},body:JSON.stringify(item.body)});if(r.ok)await NSAssistDB.deleteOutbox(id);}catch{}return;}const url=new URL("./",self.registration.scope);url.searchParams.set("assistEvent",payload.eventId||"");const openClients=await clients.matchAll({type:"window",includeUncontrolled:true});let client=openClients[0];if(client){await client.focus();client.postMessage({type:"assist-open",payload});}else client=await clients.openWindow(url.href);})())});
