import http from 'node:http';import {randomBytes,timingSafeEqual} from 'node:crypto';import {existsSync,mkdirSync,readFileSync,writeFileSync} from 'node:fs';import {fileURLToPath} from 'node:url';import {join} from 'node:path';import webpush from 'web-push';import {Store} from './store.mjs';
const root=fileURLToPath(new URL('.',import.meta.url)),privateDir=join(root,'private');mkdirSync(privateDir,{recursive:true});const configFile=join(privateDir,'config.json');
if(!existsSync(configFile))writeFileSync(configFile,JSON.stringify({registrationCode:process.env.NS_REGISTRATION_CODE||randomBytes(12).toString('hex'),vapid:webpush.generateVAPIDKeys()}));const config=JSON.parse(readFileSync(configFile));
const allowedOrigin=process.env.NS_ALLOWED_ORIGIN||'http://127.0.0.1:8080';webpush.setVapidDetails(process.env.NS_VAPID_SUBJECT||'https://github.com/kuwamelody-cloud/netsuper-daily-app',config.vapid.publicKey,config.vapid.privateKey);const store=new Store(join(privateDir,'state.json'));
const json=(res,status,data,origin)=>{res.writeHead(status,{'Content-Type':'application/json; charset=utf-8','Cache-Control':'no-store','Access-Control-Allow-Origin':origin||allowedOrigin,'Vary':'Origin'});res.end(JSON.stringify(data));};
const sameOrigin=req=>{const origin=req.headers.origin||allowedOrigin;return origin===allowedOrigin?origin:null;};
const authorized=req=>{const token=(req.headers.authorization||'').replace(/^Bearer /,'');return store.installationByToken(token);};
async function body(req){let raw='';for await(const chunk of req){raw+=chunk;if(raw.length>40000)throw Error('送信内容が大きすぎます');}return JSON.parse(raw||'{}');}
function validSubscription(s){try{const u=new URL(s.endpoint);return u.protocol==='https:'&&!u.username&&!u.password&&!u.port&&['web.push.apple.com','fcm.googleapis.com','updates.push.services.mozilla.com'].includes(u.hostname)&&Buffer.from(s.keys.p256dh,'base64url').length===65&&Buffer.from(s.keys.auth,'base64url').length===16;}catch{return false;}}
const server=http.createServer(async(req,res)=>{const origin=sameOrigin(req);if(!origin)return json(res,403,{error:'許可されていない接続元です'},allowedOrigin);if(req.method==='OPTIONS'){res.writeHead(204,{'Access-Control-Allow-Origin':origin,'Access-Control-Allow-Headers':'Authorization, Content-Type','Access-Control-Allow-Methods':'GET, POST, OPTIONS','Access-Control-Max-Age':'600','Vary':'Origin'});return res.end();}
  try{const path=new URL(req.url,'http://localhost').pathname;if(path==='/health')return json(res,200,{ok:true},origin);if(path==='/api/config')return json(res,200,{publicKey:config.vapid.publicKey},origin);if(req.method!=='POST'&&path!=='/api/state')return json(res,405,{error:'Method not allowed'},origin);const input=req.method==='POST'?await body(req):{};
    if(path==='/api/install'){let installation=authorized(req);if(!installation){const supplied=Buffer.from(String(input.registrationCode||'')),expected=Buffer.from(config.registrationCode);if(supplied.length!==expected.length||!timingSafeEqual(supplied,expected))return json(res,401,{error:'接続コードが違います'},origin);if(!validSubscription(input.subscription))return json(res,400,{error:'Push購読が不正です'},origin);installation=store.install(input.subscription);}else if(input.subscription&&validSubscription(input.subscription)){installation.subscription=input.subscription;installation.updatedAt=Date.now();store.persist();}return json(res,200,{token:installation.token},origin);}
    const installation=authorized(req);if(!installation)return json(res,401,{error:'通知サーバーへ再接続してください'},origin);
    if(path==='/api/state')return json(res,200,store.snapshot(installation.id),origin);
    if(path==='/api/session/start')return json(res,200,store.start(installation.id,input),origin);
    if(path==='/api/session/routes')return json(res,200,store.updateRoutes(installation.id,input.sessionId,input.routes),origin);
    if(path==='/api/action')return json(res,200,store.action(installation.id,{...input,actionId:input.actionId||randomBytes(12).toString('hex')}),origin);
    if(path==='/api/session/end')return json(res,200,store.end(installation.id,input.sessionId,input.reason),origin);
    return json(res,404,{error:'Not found'},origin);
  }catch(e){return json(res,400,{error:e.message},origin);}});
let busy=false;async function dispatch(){if(busy)return;busy=true;try{const item=store.claim();if(!item)return;const {session,reminder,attempt,installation}=item;if(!installation?.subscription){attempt.status='no-subscription';store.persist();return;}const payload={sessionId:session.id,eventId:reminder.id,type:reminder.type,title:reminder.title,body:reminder.body,requiresAction:reminder.requiresAction,actions:reminder.actions,voiceKey:reminder.voiceKey,repeat:reminder.repeat,attempt:attempt.number,sentAt:attempt.at};try{await webpush.sendNotification(installation.subscription,JSON.stringify(payload),{TTL:60,urgency:'high',topic:Buffer.from(reminder.eventId).toString('base64url').slice(0,32),timeout:15000});attempt.status='accepted';store.log('push-accepted',{sessionId:session.id,eventId:reminder.eventId,attemptId:attempt.id});}catch(e){attempt.status='failed';attempt.statusCode=e.statusCode||null;if([404,410].includes(e.statusCode)){installation.subscription=null;session.active=false;}store.log('push-failed',{sessionId:session.id,eventId:reminder.eventId,statusCode:e.statusCode||null});}}finally{busy=false;}}
setInterval(()=>dispatch().catch(()=>{}),1000);const host=process.env.HOST||'0.0.0.0';server.listen(Number(process.env.PORT||8787),host,()=>console.log(`NS business assist backend listening on ${host}:${server.address().port}`));
