import test from 'node:test';import assert from 'node:assert/strict';import {mkdtempSync,rmSync} from 'node:fs';import {tmpdir} from 'node:os';import {join} from 'node:path';import {Store} from '../store.mjs';
function fixture(t){const dir=mkdtempSync(join(tmpdir(),'ns-assist-'));t.after(()=>rmSync(dir,{recursive:true,force:true}));const s=new Store(join(dir,'state.json'));s.data.installations.i={id:'i',token:'token',subscription:{endpoint:'x'}};return s;}
const input=(now,maxAttempts=2)=>({session:{id:'s',date:'2026-09-26',startedAt:now,routes:{1:null}},schedule:[{id:'dispatch',type:'dispatch',dueAt:now+60000,title:'t',body:'b',requiresAction:true,maxAttempts,retryDelayMs:300000,actions:[['done','入力済み']]}]});
test('first send and only one five-minute retry survive restart',t=>{const s=fixture(t);s.start('i',input(1000),1000);assert.equal(s.claim(60999),null);assert.equal(s.claim(61000).attempt.number,1);const r=new Store(s.file);assert.equal(r.claim(360999),null);assert.equal(r.claim(361000).attempt.number,2);assert.equal(new Store(s.file).claim(700000),null);});
test('done cancels retry and is idempotent',t=>{const s=fixture(t);s.start('i',input(1000),1000);s.claim(61000);s.action('i',{sessionId:'s',eventId:'dispatch',action:'done',actionId:'a'},70000);s.action('i',{sessionId:'s',eventId:'dispatch',action:'done',actionId:'a'},80000);assert.equal(s.claim(361000),null);assert.equal(s.data.actions.length,1);});
test('pending does not postpone retry',t=>{const s=fixture(t);s.start('i',input(1000),1000);s.claim(61000);s.action('i',{sessionId:'s',eventId:'dispatch',action:'pending',actionId:'p'},70000);assert.equal(s.claim(361000).attempt.number,2);});
test('route zero cancels future route notice and can restore before due',t=>{const s=fixture(t);const x=input(1000,1);x.schedule[0].route=1;s.start('i',x,1000);s.updateRoutes('i','s',{1:0},2000);assert.equal(s.data.sessions.s.reminders[0].cancelled,true);s.updateRoutes('i','s',{1:3},3000);assert.equal(s.data.sessions.s.reminders[0].cancelled,false);});
test('ending session cancels all future reminders',t=>{const s=fixture(t);s.start('i',input(1000),1000);s.end('i','s','ended',2000);assert.equal(s.claim(61000),null);assert.equal(s.data.sessions.s.active,false);});
test('stale reminder expires instead of replaying',t=>{const s=fixture(t);s.start('i',input(1000),1000);assert.equal(s.claim(122000),null);assert.equal(s.data.sessions.s.reminders[0].cancelReason,'expired');});
